<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <AssemblyName>Microsoft.EntityFrameworkCore.InMemory.Tests</AssemblyName>
    <RootNamespace>Microsoft.EntityFrameworkCore</RootNamespace>
    <ImplicitUsings>true</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Remote.Linq.Newtonsoft.Json" />
    <PackageReference Include="Serialize.Linq" />
  </ItemGroup>
  
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Xunit.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EfCore.Client\EfCore.Client.csproj" />
  </ItemGroup>

</Project>
